package com.traderepublic.atrposki;

/*
 * @author aleksandartrposki@gmail.com
 * @since 14.07.19
 *
 *
 */

import com.fasterxml.jackson.databind.ObjectMapper;
import com.traderepublic.atrposki.core.TimeProvider;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import java.sql.Timestamp;
import java.time.LocalDateTime;

@SpringBootApplication
@EnableAutoConfiguration
@Configuration
@ComponentScan({"com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables", "com.traderepublic.atrposki"})
public class Microservice {
    public static void main(String[] args) {
        SpringApplication.run(Microservice.class, args);
    }

    @Bean
    public ObjectMapper objectMapper() {
        return new ObjectMapper();
    }

    @Bean
    TimeProvider timeProvider() {
        return new TimeProvider() {
            @Override
            public Timestamp now() {
                return Timestamp.valueOf(LocalDateTime.now());
            }

            @Override
            public Timestamp beforeMinutes(int minutes) {
                LocalDateTime res = this.now().toLocalDateTime().minusMinutes(minutes);
                return Timestamp.valueOf(res);
            }
        };
    }
}
