/*
 * This file is generated by jOOQ.
 */
package com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_;


import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.InstrumentEvent;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.InstrumentHotnessChangeEvent;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.PriceEvent;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index INDEX_EVENT_ISIN = Indexes0.INDEX_EVENT_ISIN;
    public static final Index PRIMARY_KEY_3 = Indexes0.PRIMARY_KEY_3;
    public static final Index INSTRUMENT_HOTNESS_CHANGE_EVENT_ISIN = Indexes0.INSTRUMENT_HOTNESS_CHANGE_EVENT_ISIN;
    public static final Index INSTRUMENT_HOTNESS_CHANGE_EVENT_TIMESTAMP = Indexes0.INSTRUMENT_HOTNESS_CHANGE_EVENT_TIMESTAMP;
    public static final Index PRIMARY_KEY_D = Indexes0.PRIMARY_KEY_D;
    public static final Index PRICE_EVENT_DAY = Indexes0.PRICE_EVENT_DAY;
    public static final Index PRICE_EVENT_HOUR = Indexes0.PRICE_EVENT_HOUR;
    public static final Index PRICE_EVENT_ISIN = Indexes0.PRICE_EVENT_ISIN;
    public static final Index PRICE_EVENT_MINUTE = Indexes0.PRICE_EVENT_MINUTE;
    public static final Index PRICE_EVENT_MONTH = Indexes0.PRICE_EVENT_MONTH;
    public static final Index PRICE_EVENT_TIMESTAMP = Indexes0.PRICE_EVENT_TIMESTAMP;
    public static final Index PRICE_EVENT_YEAR = Indexes0.PRICE_EVENT_YEAR;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index INDEX_EVENT_ISIN = Internal.createIndex("INDEX_EVENT_ISIN", InstrumentEvent.INSTRUMENT_EVENT, new OrderField[] { InstrumentEvent.INSTRUMENT_EVENT.ISIN }, false);
        public static Index PRIMARY_KEY_3 = Internal.createIndex("PRIMARY_KEY_3", InstrumentEvent.INSTRUMENT_EVENT, new OrderField[] { InstrumentEvent.INSTRUMENT_EVENT.ID }, true);
        public static Index INSTRUMENT_HOTNESS_CHANGE_EVENT_ISIN = Internal.createIndex("INSTRUMENT_HOTNESS_CHANGE_EVENT_ISIN", InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT, new OrderField[] { InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT.ISIN }, false);
        public static Index INSTRUMENT_HOTNESS_CHANGE_EVENT_TIMESTAMP = Internal.createIndex("INSTRUMENT_HOTNESS_CHANGE_EVENT_TIMESTAMP", InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT, new OrderField[] { InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT.TIMESTAMP }, false);
        public static Index PRIMARY_KEY_D = Internal.createIndex("PRIMARY_KEY_D", InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT, new OrderField[] { InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT.ID }, true);
        public static Index PRICE_EVENT_DAY = Internal.createIndex("PRICE_EVENT_DAY", PriceEvent.PRICE_EVENT, new OrderField[] { PriceEvent.PRICE_EVENT.DAY }, false);
        public static Index PRICE_EVENT_HOUR = Internal.createIndex("PRICE_EVENT_HOUR", PriceEvent.PRICE_EVENT, new OrderField[] { PriceEvent.PRICE_EVENT.HOUR }, false);
        public static Index PRICE_EVENT_ISIN = Internal.createIndex("PRICE_EVENT_ISIN", PriceEvent.PRICE_EVENT, new OrderField[] { PriceEvent.PRICE_EVENT.ISIN }, false);
        public static Index PRICE_EVENT_MINUTE = Internal.createIndex("PRICE_EVENT_MINUTE", PriceEvent.PRICE_EVENT, new OrderField[] { PriceEvent.PRICE_EVENT.MINUTE }, false);
        public static Index PRICE_EVENT_MONTH = Internal.createIndex("PRICE_EVENT_MONTH", PriceEvent.PRICE_EVENT, new OrderField[] { PriceEvent.PRICE_EVENT.MONTH }, false);
        public static Index PRICE_EVENT_TIMESTAMP = Internal.createIndex("PRICE_EVENT_TIMESTAMP", PriceEvent.PRICE_EVENT, new OrderField[] { PriceEvent.PRICE_EVENT.TIMESTAMP }, false);
        public static Index PRICE_EVENT_YEAR = Internal.createIndex("PRICE_EVENT_YEAR", PriceEvent.PRICE_EVENT, new OrderField[] { PriceEvent.PRICE_EVENT.YEAR }, false);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", PriceEvent.PRICE_EVENT, new OrderField[] { PriceEvent.PRICE_EVENT.ID }, true);
    }
}
