/*
 * This file is generated by jOOQ.
 */
package com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_;


import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.InstrumentEvent;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.InstrumentHotnessChangeEvent;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.PriceEvent;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.records.InstrumentEventRecord;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.records.InstrumentHotnessChangeEventRecord;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.records.PriceEventRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<InstrumentEventRecord, Integer> IDENTITY_INSTRUMENT_EVENT = Identities0.IDENTITY_INSTRUMENT_EVENT;
    public static final Identity<InstrumentHotnessChangeEventRecord, Integer> IDENTITY_INSTRUMENT_HOTNESS_CHANGE_EVENT = Identities0.IDENTITY_INSTRUMENT_HOTNESS_CHANGE_EVENT;
    public static final Identity<PriceEventRecord, Integer> IDENTITY_PRICE_EVENT = Identities0.IDENTITY_PRICE_EVENT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<InstrumentEventRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<InstrumentHotnessChangeEventRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
    public static final UniqueKey<PriceEventRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<InstrumentEventRecord, Integer> IDENTITY_INSTRUMENT_EVENT = Internal.createIdentity(InstrumentEvent.INSTRUMENT_EVENT, InstrumentEvent.INSTRUMENT_EVENT.ID);
        public static Identity<InstrumentHotnessChangeEventRecord, Integer> IDENTITY_INSTRUMENT_HOTNESS_CHANGE_EVENT = Internal.createIdentity(InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT, InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT.ID);
        public static Identity<PriceEventRecord, Integer> IDENTITY_PRICE_EVENT = Internal.createIdentity(PriceEvent.PRICE_EVENT, PriceEvent.PRICE_EVENT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<InstrumentEventRecord> CONSTRAINT_3 = Internal.createUniqueKey(InstrumentEvent.INSTRUMENT_EVENT, "CONSTRAINT_3", InstrumentEvent.INSTRUMENT_EVENT.ID);
        public static final UniqueKey<InstrumentHotnessChangeEventRecord> CONSTRAINT_D = Internal.createUniqueKey(InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT, "CONSTRAINT_D", InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT.ID);
        public static final UniqueKey<PriceEventRecord> CONSTRAINT_2 = Internal.createUniqueKey(PriceEvent.PRICE_EVENT, "CONSTRAINT_2", PriceEvent.PRICE_EVENT.ID);
    }
}
