/*
 * This file is generated by jOOQ.
 */
package com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_;


import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.InstrumentEvent;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.InstrumentHotnessChangeEvent;
import com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.PriceEvent;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.INSTRUMENT_EVENT</code>.
     */
    public static final InstrumentEvent INSTRUMENT_EVENT = com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.InstrumentEvent.INSTRUMENT_EVENT;

    /**
     * The table <code>PUBLIC.INSTRUMENT_HOTNESS_CHANGE_EVENT</code>.
     */
    public static final InstrumentHotnessChangeEvent INSTRUMENT_HOTNESS_CHANGE_EVENT = com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.InstrumentHotnessChangeEvent.INSTRUMENT_HOTNESS_CHANGE_EVENT;

    /**
     * The table <code>PUBLIC.PRICE_EVENT</code>.
     */
    public static final PriceEvent PRICE_EVENT = com.traderepublic.atrposki.autogenerated.jooq.partnereventstream.public_.tables.PriceEvent.PRICE_EVENT;
}
